name: Code checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - "FastRag/**"

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for UV
        uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: 'pyproject.toml'
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run blackâ¬›
        run: |
          uv run black --check --diff ./
      - name: Run mypy ğŸ”
        run: |
          uv run mypy FastRag
      - name: Check commit messages ğŸ’¬
        run: |
          uv run cz check
      - name: Run ruff ğŸ›‚
        run: |
          uv run ruff check . --no-fix
